#pragma once
class SwapChain;
class DeviceContext;
class VertexBuffer;
class VertexShader;
class PixelShader;
class ConstantBuffer;
class IndexBuffer;
class UIManager;
class RenderSystem;
class GraphicsEngine;